SYNONYMS = {
    "std": "standard",
    "aut": "automatico",
    "auto": "automatico",
    "mt": "manual",
    "at": "automatico",
    "p": "puertas",
    "ptas": "puertas",
    "cil": "cilindros",
    "ac": "aire acondicionado",
    "aa": "aire acondicionado",
    "dh": "direccion hidraulica",
    "ve": "vidrios electricos",
    "quemacocos": "quemacocos",
    "qc": "quemacocos",
    "piel": "asientos de piel",
    "tela": "asientos de tela",
    "abs": "frenos abs",
    "ab": "bolsa de aire",
    "airbag": "bolsa de aire",
    "cd": "reproductor cd",
    "mp3": "reproductor mp3",
    "usb": "puerto usb",
    "aux": "entrada auxiliar",
    "bt": "bluetooth",
    "gps": "navegacion",
    "nav": "navegacion",
    "4x2": "traccion dos ruedas",
    "4x4": "traccion cuatro ruedas",
    "awd": "traccion total",
    "fwd": "traccion delantera",
    "rwd": "traccion trasera",
    "hb": "hatchback",
    "sdn": "sedan",
    "suv": "camioneta",
    "pu": "pickup",
    "minivan": "minivan",
    "van": "furgoneta",
    "coupe": "coupe",
    "cab": "cabina",
    "reg": "regular",
    "ext": "extendida",
    "dbl": "doble",
    "crew": "doble",
    "l4": "4 cilindros",
    "v6": "6 cilindros",
    "v8": "8 cilindros",
    "hev": "hibrido",
    "phev": "hibrido enchufable",
    "mhev": "micro hibrido",
    "t": "turbo",
    "l": "litros",
    "hp": "caballos de fuerza",
    "cp": "caballos de fuerza",
    "cv": "caballos de vapor",
}
